# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.2.0-beta.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"
  bash_completion "completions/rune.bash"
  zsh_completion "completions/rune.zsh"
  fish_completion "completions/rune.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.6/rune_Darwin_x86_64.tar.gz"
      sha256 "ff92ea76ca0edded81e886341c976e3a02ab901464b29bc4a75585762f7d2fe3"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.6/rune_Darwin_arm64.tar.gz"
      sha256 "03cee71de63a4f4cf3c867d72ad123ed9ddb50b02436a6fe2df4e70b126ef78a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.6/rune_Linux_x86_64.tar.gz"
      sha256 "84a7ecc22f2b11887045929c39d7f0080f7b544c8cdd748f74f275ab29c6d8f1"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.6/rune_Linux_arm64.tar.gz"
      sha256 "93de96d02b02b090491be3bd050f879943621c807596bb5900a3e9538a8af7ec"
    end
  end

  postflight do
    # Create default config directory
    system_command "/bin/mkdir", args: ["-p", "#{ENV['HOME']}/.rune"]
  end

  caveats do
    "To get started with rune:"
    "  1. Initialize your configuration: rune init --guided"
    "  2. Start your workday: rune start"
    "  3. Check status: rune status"
    "  4. End your workday: rune stop"
    ""
    "Configuration file location: ~/.rune/config.yaml"
    ""
    "For more information, visit: https://github.com/ferg-cod3s/rune"
  end

  # No zap stanza required
end
