# This file was generated by GoReleaser. DO NOT EDIT.
cask "rune" do
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.2.0-beta.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rune"
  bash_completion "completions/rune.bash"
  zsh_completion "completions/rune.zsh"
  fish_completion "completions/rune.fish"
  depends_on formula: [
      "git",
    ]

  on_macos do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.3/rune_Darwin_x86_64.tar.gz"
      sha256 "1c04ad89fc9c9388c6caa5bf789ae36499a25cfa483a502728f35c498abf1114"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.3/rune_Darwin_arm64.tar.gz"
      sha256 "e7c3f85b2ab72c8a32e27b514d7bd444e78b2e03a05bc36eefc4ef05f513d5a3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.3/rune_Linux_x86_64.tar.gz"
      sha256 "f7c254743533b58fa9e7c91e1f942e1f94a3666f063cb81d72e622544f2c2546"
    end
    on_arm do
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.2.0-beta.3/rune_Linux_arm64.tar.gz"
      sha256 "55c8fcf83702dc347b8839e128627425e710cf6fd3213d6bab12f460359a0620"
    end
  end

  postflight do
    # Create default config directory
    system_command "/bin/mkdir", args: ["-p", "#{ENV['HOME']}/.rune"]
  end

  caveats do
    "To get started with rune:"
    "  1. Initialize your configuration: rune init --guided"
    "  2. Start your workday: rune start"
    "  3. Check status: rune status"
    "  4. End your workday: rune stop"
    ""
    "Configuration file location: ~/.rune/config.yaml"
    ""
    "For more information, visit: https://github.com/ferg-cod3s/rune"
  end

  # No zap stanza required
end
