# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotunnel < Formula
  desc "CLI tool for local network tunnel to web applications via .local domains"
  homepage "https://github.com/v1truv1us/gotunnel"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/gotunnel/releases/download/v0.2.0/gotunnel_Darwin_x86_64.tar.gz"
      sha256 "8c0d2c8b50cf701a6dd78b0c02411982646e8702b9ef8bb999d76839fd815f59"

      def install
        bin.install "gotunnel"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/gotunnel/releases/download/v0.2.0/gotunnel_Darwin_arm64.tar.gz"
      sha256 "a5e4ac0c84486a4af36b35d39eb2b04b09415d01a995f88d22e075611e6d39bf"

      def install
        bin.install "gotunnel"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/gotunnel/releases/download/v0.2.0/gotunnel_Linux_x86_64.tar.gz"
      sha256 "36422420444828bb6eaec05980c9b8723355347a3f93974fa7b7ec6f3b792a59"

      def install
        bin.install "gotunnel"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/gotunnel/releases/download/v0.2.0/gotunnel_Linux_arm64.tar.gz"
      sha256 "06425e95ea47a78f1fb02302b0296d0808f78a55948ed88901806fedd178b82c"

      def install
        bin.install "gotunnel"
      end
    end
  end

  def caveats
    <<~EOS
      Gotunnel enables .local domain access to local web apps.

      Usage:
        gotunnel serve --port 3000
        gotunnel list

      For more info: https://github.com/v1truv1us/gotunnel
    EOS
  end

  test do
    system "#{bin}/gotunnel", "--help"
  end
end