# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ninjops < Formula
  desc "CLI tool for ninja-style development workflow automation"
  homepage "https://github.com/v1truv1us/ninjops"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/ninjops/releases/download/v0.1.0/ninjops_0.1.0_darwin_amd64.tar.gz"
      sha256 "447f3b242e1436d3b64ced44bd9826f7a028e3da5b7e35bf9ca5489662edab4d"

      def install
        bin.install "ninjops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/ninjops/releases/download/v0.1.0/ninjops_0.1.0_darwin_arm64.tar.gz"
      sha256 "05d1b0a1e1b3c0b2f2b78f2116e5883e8aceb506e730ad6c4f90c5182a11f86a"

      def install
        bin.install "ninjops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/ninjops/releases/download/v0.1.0/ninjops_0.1.0_linux_amd64.tar.gz"
      sha256 "af3ddf9f6246c925e06e7fd1be619742d713588cb84e63ab11831165c8c2dcce"

      def install
        bin.install "ninjops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/ninjops/releases/download/v0.1.0/ninjops_0.1.0_linux_arm64.tar.gz"
      sha256 "0bf6c34c755bc42f1a7e80f6eee3c9239d72a079fabb4a5380345ddc5bb980ea"

      def install
        bin.install "ninjops"
      end
    end
  end

  test do
    system "#{bin}/ninjops", "--help"
  end
end