# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rune < Formula
  desc "Ancient wisdom for modern workflows - A developer-first CLI productivity platform"
  homepage "https://github.com/ferg-cod3s/rune"
  version "0.1.0-alpha.17"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.17/rune_Darwin_x86_64.tar.gz"
      sha256 "9991766ec114ec94a4eff02dcae2aa541f1f82f024ee5a560e9de6d12173f90b"

      def install
        bin.install "rune"

        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        (etc/"rune").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.17/rune_Darwin_arm64.tar.gz"
      sha256 "4134b7d723d694f3bdb0d9396dc12a0b477de2e68b7f35e6ca94f8d5aa848b79"

      def install
        bin.install "rune"

        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        (etc/"rune").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.17/rune_Linux_x86_64.tar.gz"
      sha256 "cda6d63352816a28fa69be530f2f1d73809c9f9333db919d9778a74c8d4db91d"
      def install
        bin.install "rune"

        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        (etc/"rune").mkpath
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/ferg-cod3s/rune/releases/download/v0.1.0-alpha.17/rune_Linux_arm64.tar.gz"
      sha256 "fbeb33dc4ebdce324c77d8f57c4157681d26f547f543b88c01b9021682b52fd0"
      def install
        bin.install "rune"

        bash_completion.install "completions/rune.bash" => "rune"
        zsh_completion.install "completions/rune.zsh" => "_rune"
        fish_completion.install "completions/rune.fish"

        (etc/"rune").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      To get started with rune:
        1. Initialize your configuration: rune init --guided
        2. Start your workday: rune start
        3. Check status: rune status
        4. End your workday: rune stop

      Configuration file location: ~/.rune/config.yaml

      For more information, visit: https://github.com/ferg-cod3s/rune
    EOS
  end

  test do
    system "#{bin}/rune", "--version"
    system "#{bin}/rune", "--help"
  end
end