# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solo < Formula
  desc "Local orchestration layer for coordinating multiple coding agents"
  homepage "https://github.com/v1truv1us/Solo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.0/Solo_Darwin_x86_64.tar.gz"
      sha256 "5122b9b37b2e326062eaae7604bba8b205beeddb12fa3245bbed44807b0eee84"

      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.0/Solo_Darwin_arm64.tar.gz"
      sha256 "68a1508f5cbd00855efeeba28447630523f94b5c1a1bae5a1f55e48438ca0acf"

      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.0/Solo_Linux_x86_64.tar.gz"
      sha256 "c30edd6141a40eeb9b760e174bd78a120017b1c5dccba1a17aec2f06df833f25"
      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.0/Solo_Linux_arm64.tar.gz"
      sha256 "e63f9496e7405b642b7351f0ac1b51c43729705ca43a389fc2292b54af8bf70f"
      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Solo:

        1. Initialize a repository:  solo init
        2. Create a task:            solo task create --title "My task" --priority high
        3. Start a session:          solo session start T-1 --worker claude-code
        4. Complete or hand off:     solo session end T-1 --result completed

      For more information, visit: https://github.com/v1truv1us/Solo
    EOS
  end

  test do
    system "#{bin}/solo", "--help"
    system "#{bin}/solo", "health", "--json"
  end
end
