# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Solo < Formula
  desc "Local orchestration layer for coordinating multiple coding agents"
  homepage "https://github.com/v1truv1us/Solo"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_x86_64.tar.gz"
      sha256 "64789e07b9e946621f16584dffe81b1a658f3456ee3d3e0abf7c1374dbe3adaf"

      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Darwin_arm64.tar.gz"
      sha256 "a5cbee6eb7b50d35c64dc48b5e6799e554751298215e961d6ff4c1b9064109d1"

      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_x86_64.tar.gz"
      sha256 "b49b3e3831d02e2979a7ce1d852dbe658561a3d8414e52f197ee1d64d1b76271"
      define_method(:install) do
        bin.install "solo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/v1truv1us/Solo/releases/download/v0.1.1/Solo_Linux_arm64.tar.gz"
      sha256 "38455e4078c7397278a23ffb7775554813b662bee3fdfaaf1a2eec1a2ca79458"
      define_method(:install) do
        bin.install "solo"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with Solo:

        1. Initialize a repository:  solo init
        2. Create a task:            solo task create --title "My task" --priority high
        3. Start a session:          solo session start T-1 --worker claude-code
        4. Complete or hand off:     solo session end T-1 --result completed

      For more information, visit: https://github.com/v1truv1us/Solo
    EOS
  end

  test do
    system "#{bin}/solo", "--help"
    system "#{bin}/solo", "health", "--json"
  end
end
